[package]
name = "harbor-tray"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1.0.91"
native-windows-gui = "1.0.13"
harbor-core = { path = "../core" }
serde_yaml = "0.9.34"
